steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "asia.gcr.io/aspulse-run/applize-test-memory-app:$COMMIT_SHA",
        "--build-arg", "NPM_TOKEN=$_NPM_TOKEN", "."]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "asia.gcr.io/aspulse-run/applize-test-memory-app:$COMMIT_SHA"]
